### ISSUE TITLE
NullPointerException on ZExpression.toString()

### ISSUE THREAD

**Issue by NicolaSpreafico** [bogdan32x/ZQL#8]
Hi, I have a simple code like this
```java
String whereClause = "WHERE a = b OR c > 20";
ZqlJJParser parser = new ZqlJJParser(new StringReader(whereClause));
ZExp whereClause2 = parser.WhereClause();
System.out.println(whereClause2.toString());
```

The ```toString()``` method raise a ```NullPointerException```. Here is the stackTrace:
```java
ZUtils.isCustomFunction(String) line: 79	
ZExpression.toString() line: 198	
```

The problem at ```ZUtils.java # 79```
```java
nparam = (Integer) ZUtils.fcts.get(fct.toUpperCase());
```
is that the ```ZUtils.fcts``` variabile is ```null```, so there is ```{null}.get(...)```

As I can see from the ```ZUtils.java # 59```, the Hashtable is initialized only when I add a custom function.
```
public static void addCustomFunction(final String fct, final int noParams) {
    int params = noParams;

    if (ZUtils.fcts == null) {
        ZUtils.fcts = new Hashtable<String, Integer>();
    }

    ......
}
```
In my case I did not add any custom function, but directly call the ```toString()```

For now I fixed the problem editing the ```ZUtils.java # .38``` like this

```java
private static Hashtable<String, Integer> fcts = new Hashtable<String, Integer>();
```
so there is no more a null variable.
Feels free to resolve the problem as your own way.

Regards

**Comment by bogdan32x** [comment]
@NicolaSpreafico thanks for poiting this out. I will add some unit tests for this and fix it.
If you have a GithubBranch of ZQL please let me know. I am planning to release it on central maven repo this month and it would be nice to have any extra fixes/changes.
